name: ml_protein_protein
channels:
  - conda-forge
  - defaults
  - omnia
  - schrodinger
dependencies:
  - python=3.7
  - flake8
  - jedi
  - autopep8
  - numpy==1.19.4
  - matplotlib==3.3.3
  - pytorch
  - bayesian-optimization==1.1.0
  - xgboost==1.2.0
  - scikit-learn==0.23.2
  - munch
    # - omnia/label/cuda91::openmm
  - openmm
  - pdbfixer
  - jupyterlab
  - notebook
  - pymol-bundle
  - parmed
  - scikit-image
  - tqdm
  - torchvision
