name: ml_protein_protein
channels:
  - conda-forge
  - defaults
  - omnia
  - schrodinger
dependencies:
  - python=3.7
  - flake8
  - jedi
  - autopep8
  - numpy
  - matplotlib
  - pytorch
  - bayesian-optimization
  - xgboost
  - scikit-learn
  - munch
    # - omnia/label/cuda91::openmm
  - openmm
  - pdbfixer
  - mdtraj
  - jupyterlab
  - notebook
  - pymol-bundle
  - parmed
