name: ml_protein_protein
channels:
  - conda-forge
  - defaults
  - omnia
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pytorch
  - bayesian-optimization
  - xgboost
  - scikit-learn
  - munch
  - openmm
  - pdbfixer
